mongoUri : "mongodb://localhost:27017"
dbName : "mydb"
collectionName : "products"
elasticUri : "http://localhost:9200"
elasticUsername : "elastic"
elasticPassword : "mJquAU0Sa2cgYSyz2bnf"
elasticIndex : "products"
filePath : "last_inserted_id.csv"
readFromFile : true
attempts : 5
batchSize : 1
bufferSize : 50
