global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'data-stream'
    static_configs:
      - targets: ['data-stream:9091']

  - job_name: "mongo"
    static_configs:
      - targets: [ "mongo-exporter:9216" ]

  - job_name: "elasticsearch"
    static_configs:
      - targets: [ "elasticsearch-exporter:9114" ]